name: SELBans
description: Better banning, kicking and warning system, with stored SQL data for lookup.
main: com.domsplace.SELBans
authors: [Dominic]
website: http://domsplace.com/
version: 1.10
load: POSTWORLD
permission: You don't have permission for this.
commands:
   ban:
      description: Bans a player with a specified reason.
      usage: /<command> [player] (length) [reason]
      aliases: [tempban, banish]
   kick:
      description: Kicks a player with a specified reason.
      usage: /<command> [player] [reason]
      permission: SELBans.kick
      permission-message: §cYou don't have permission.
   warn:
      description: Warns a player with a message.
      usage: /<command> [player] [reason]
      permission: SELBans.warn
      permission-message: §cYou don't have permission.
      aliases: [warning]
   pardon:
      description: Unbans a player.
      usage: /<command> [player]
      permission: SELBans.pardon
      aliases: [unban]
      permission-message: §cYou don't have permission.
   mute:
      description: Warns a player with a message.
      usage: /<command> [player] (duration) [reason]
      aliases: [quiet, shutup, installwindowsvistakeyboarddrivers]
   demote:
      description: Demotes a player and stores the reason.
      usage: /<command> [player] [group] [reason]
      permission: SELBans.demote
      permission-message: §cYou don't have permission.
   playerinfo:
      description: Displays Player Info.
      usage: /<command> [player] (page)
      permission: SELBans.playerinfo
      permission-message: §cYou don't have permission.
      aliases: [warns, kicks, bans, mutes, demotes]
   SELBans:
      description: Reloads the SELBans Configuration.
      usage: /<command>
      permission: SELBans.reload
      permission-message: §cYou don't have permission.
permissions:
   SELBans.*:
     description: Gives access to all SELBans permissions
     default: op
     children:
       SELBans.ban: true
       SELBans.warn: true
       SELBans.kick: true
       SELBans.mute: true
       SELBans.demote: true
       SELBans.ban.notify: true
       SELBans.warn.notify: true
       SELBans.kick.notify: true
       SELBans.mute.notify: true
       SELBans.demote: true
       SELBans.unmute: true
       SELBans.playerinfo: true
       SELBans.reload: true
       SELBans.tempmute: true
       SELBans.tempmute.bypass: true
       SELBans.tempban: true
       SELBans.tempban.bypass: true
   SELBans.ban.notify:
     description: View when a player is ban.
     default: op
   SELBans.ban:
     description: Allows /ban command access, and displays notification.
     default: op
   SELBans.warn.notify:
     description: View when a player is warned.
     default: op
   SELBans.warn:
     description: Allows /warn command access, and displays notification.
     default: op
   SELBans.kick.notify:
     description: View when a player is kicked.
     default: op
   SELBans.kick:
     description: Allows /ban command access, and displays notification.
     default: op
   SELBans.mute.notify:
     description: View when a player is muted.
     default: op
   SELBans.mute:
     description: Allows /mute command access, and displays notification.
     default: op
   SELBans.unmute:
     description: Allows players to unmute other players.
     default: op
   SELBans.demote:
     description: Allows /demote command access, and displays notification.
     default: op
   SELBans.pardon:
     description: Allows /pardon command access.
     default: op
   SELBans.playerinfo:
     description: Allows /warns, /kicks, /bans, /mutes command access.
     default: op
   SELBans.reload:
     description: Allows access to reload the configuration.
     default: op
   SELBans.tempmute:
     description: Allows players to temporarily mute.
     default: op
   SELBans.tempban:
     description: Allows players to temporarily ban.
     default: op
   SELBans.tempmute.bypass:
     description: Bypass the temporary mute max time.
     default: op
   SELBans.tempban.bypass:
     description: Bypass the temporary ban max time.
     default: op